# Generated by Django 3.1.4 on 2021-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=120, null=True)),
                ('lightBg', models.BooleanField()),
                ('lightText', models.BooleanField()),
                ('lightTextDesc', models.BooleanField()),
                ('headline', models.CharField(blank=True, max_length=2000, null=True)),
                ('buttonLabel', models.CharField(blank=True, max_length=300, null=True)),
                ('imgStart', models.BooleanField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('alt', models.CharField(max_length=120)),
                ('dark', models.BooleanField()),
                ('primary', models.BooleanField()),
                ('darkText', models.BooleanField()),
            ],
        ),
    ]
