# Generated by Django 3.1.4 on 2021-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='topline',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
