# Generated by Django 3.2.7 on 2021-10-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mailchimpemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
