# Generated by Django 3.2.7 on 2021-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('feature_1', models.CharField(blank=True, max_length=510, null=True)),
                ('feature_2', models.CharField(blank=True, max_length=510, null=True)),
                ('feature_3', models.CharField(blank=True, max_length=510, null=True)),
                ('feature_4', models.CharField(blank=True, max_length=510, null=True)),
                ('feature_5', models.CharField(blank=True, max_length=510, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
