# Generated by Django 3.2.7 on 2021-11-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_order_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_through_buy_now_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=510, null=True),
        ),
    ]
